no1 = int(input("Choose Your First Number"))
no2= int(input("Choose Your Second Number"))
print(no1,"+",no2,"=",(no1+no2))
print(no1,"-",no2,"=",(no1-no2))
print(no1,"*",no2,"=",(no1*no2))
print(no1,"/",no2,"=",(no1/no2))
